version = "2"
bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"
db_path = "/data/kanidm.db"
tls_chain = "/cert/cert.pem"
tls_key = "/cert/key.pem"
domain = "idm.rtcid.ru"
origin = "https://ru1.idm.rtcid.ru"

[http_client_address_info]
x-forward-for = ["172.16.0.0/16", "fd55:b5ae:10f8::/64"]

[replication]
origin = "repl://ru1.romixthecat.cc:8444"
bindaddress = "[::]:8444"

[replication."repl://nl1.romixthecat.cc:8444"]
type = "mutual-pull"
partner_cert = "MIICBTCCAaqgAwIBAgIBATAKBggqhkjOPQQDAjBMMRswGQYDVQQKDBJLYW5pZG0gUmVwbGljYXRpb24xLTArBgNVBAMMJDU0ZDgyNDgwLWJkOGItNGVkMC04NjExLTQwMmZiYWY5OTNiMzAeFw0yNTEwMzEyMDIyMDlaFw0yOTEwMzEyMDIyMDlaMEwxGzAZBgNVBAoMEkthbmlkbSBSZXBsaWNhdGlvbjEtMCsGA1UEAwwkNTRkODI0ODAtYmQ4Yi00ZWQwLTg2MTEtNDAyZmJhZjk5M2IzMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErChA3UXBcd1i0ed_P746J2CefdtB38-0L80dc-7tE5E5xcLY_iSiBLCTYld_8O_g13CXeIJftdAgKlthbRe7VqN9MHswDAYDVR0TAQH_BAIwADAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBTaOaPuXmtLDTJVv--VYBiQr9gHCTAdBgNVHREEFjAUghJubDEucm9taXh0aGVjYXQuY2MwCgYIKoZIzj0EAwIDSQAwRgIhAP3Eb641nQmE8xMQOGeHz_98hIcOMiAzIQ3L_bC8TwMJAiEAwB2TYf9wZXhQVVL7BuHzAOHTRyZhv6OH67v9hSx5Os8="

[replication."repl://ru2.romixthecat.cc:8444"]
type = "mutual-pull"
partner_cert = "MIICBDCCAaqgAwIBAgIBATAKBggqhkjOPQQDAjBMMRswGQYDVQQKDBJLYW5pZG0gUmVwbGljYXRpb24xLTArBgNVBAMMJDJhMGM2NzY0LTIyODktNDMyYi05NGMzLTA2MTc0MzRlM2EwZTAeFw0yNTExMDcxNzMzMDRaFw0yOTExMDcxNzMzMDRaMEwxGzAZBgNVBAoMEkthbmlkbSBSZXBsaWNhdGlvbjEtMCsGA1UEAwwkMmEwYzY3NjQtMjI4OS00MzJiLTk0YzMtMDYxNzQzNGUzYTBlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQ4HBcfYDKm1gYX3ZVfSzWsPYCKSqXHCQ9a-ICZdcuWmErS2YXJIAmIsRJKRdoZaqY0HA3Y91EgavULO8wJTtaqN9MHswDAYDVR0TAQH_BAIwADAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBTaOaPuXmtLDTJVv--VYBiQr9gHCTAdBgNVHREEFjAUghJydTIucm9taXh0aGVjYXQuY2MwCgYIKoZIzj0EAwIDSAAwRQIgG6k6O9roFi2evHbAzBq_uuhEZRvBQY1QiJgJsblH5ysCIQC0FHlho_VD40ynL09F5dG4KXXW6OZrzMjKGotKfVmZIg=="
