http:
  serversTransports:
    idm-nl1:
      serverName: "nl1.idm.rtcid.ru"
      rootcas:
        - /certs/idm.pem
    idm-ru1:
      serverName: "ru1.idm.rtcid.ru"
      rootcas:
        - /certs/idm.pem
    idm-ru2:
      serverName: "ru2.idm.rtcid.ru"
      rootcas:
        - /certs/idm.pem
